---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: example-io-selfsigned
  namespace: music-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-io-selfsigned
  namespace: music-system
spec:
  dnsNames:
    - example.io
  secretName: example-io-selfsigned-cert-tls
  issuerRef:
    name: example-io-selfsigned
