
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - music.example.io
  resources:
  - rockbands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - music.example.io
  resources:
  - rockbands/status
  verbs:
  - get
  - patch
  - update
