# permissions for end users to view rockbands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rockband-viewer-role
rules:
- apiGroups:
  - music.example.io
  resources:
  - rockbands
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - music.example.io
  resources:
  - rockbands/status
  verbs:
  - get
