# permissions for end users to edit rockbands.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rockband-editor-role
rules:
- apiGroups:
  - music.example.io
  resources:
  - rockbands
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - music.example.io
  resources:
  - rockbands/status
  verbs:
  - get
